-- flio.product definition

CREATE TABLE `product` (
  `product_id` int NOT NULL AUTO_INCREMENT COMMENT '물품 ID',
  `title` varchar(250) NOT NULL COMMENT '제목',
  `content` varchar(4000) NOT NULL COMMENT '내용',
  `select_cnt` int DEFAULT '0' COMMENT '물품 조회수',
  `category_depth1` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '카테고리1뎁스',
  `category_depth2` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '카테고리2뎁스',
  `category_option` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '카테고리옵션',
  `sale_yn` char(1) DEFAULT 'S' COMMENT '물품 판매여부(Y: 판매완료, R: 예약중, S: 판매중)',
  `tag` varchar(400) DEFAULT NULL COMMENT '태그',
  `base_url` varchar(400) DEFAULT NULL COMMENT '저장위치',
  `image_url` varchar(400) DEFAULT NULL COMMENT '이미지URL',
  `use_date` varchar(200) DEFAULT NULL COMMENT '사용기간',
  `purchase_kind` varchar(200) DEFAULT NULL COMMENT '구매방법',
  `box_yn` char(1) DEFAULT 'N' COMMENT '제품박스유무',
  `brand` varchar(200) DEFAULT NULL COMMENT '제조사이름',
  `purpose` varchar(200) DEFAULT NULL COMMENT '용도',
  `model_no` varchar(200) DEFAULT NULL COMMENT '모델명넘버',
  `serial_no` varchar(200) DEFAULT NULL COMMENT '시리얼넘버',
  `repair_yn` char(1) DEFAULT 'N' COMMENT '제품수리이력여부',
  `product_related_url` varchar(400) DEFAULT NULL COMMENT '제품관련URL',
  `uid` varchar(250) DEFAULT NULL COMMENT '판매자 UID',
  `reg_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '물품 등록날짜',
  `chg_date` timestamp NULL DEFAULT NULL COMMENT '물품 변경날짜',
  `product_price` int DEFAULT '0' COMMENT '판매가격',
  `flio_yn` char(1) DEFAULT 'N' COMMENT '플리오 여',
  `target_uid` varchar(250) DEFAULT NULL COMMENT '구매자 UID',
  `faith_yn` char(1) DEFAULT 'N' COMMENT '구매자 믿음 여부',
  `trade_kind` varchar(200) DEFAULT NULL COMMENT '거래방법',
  `product_review` char(1) DEFAULT NULL COMMENT '리뷰내용 A/B/C/D/E',
  PRIMARY KEY (`product_id`)
) ENGINE=InnoDB AUTO_INCREMENT=88 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='물품';